Change branch/tag to use
The action had failed because it couldn't find the version:
  Error: Unable to resolve action `gcapes/rocrate-to-pages@latest`,
  unable to find version `latest`